import { useState, useEffect } from "react";
import { supabase } from './supabase';
import ProjectView from './ProjectView';
import { uid, AD, FL, GM, P, $, PCT, calcStats, mkSample, USERS } from './helpers';

function LoginScreen({users,onLogin}){
  const[email,setEmail]=useState("");const[pw,setPw]=useState("");const[err,setErr]=useState("");const[sh,setSh]=useState(false);
  const go=()=>{setErr("");if(!email||!pw){setErr("Enter both fields");return;}const u=users.find(u=>u.email.toLowerCase()===email.trim().toLowerCase());if(!u){setErr("Email not found");return;}if(u.pw!==pw){setErr("Wrong password");return;}onLogin(u.id);};
  return <div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"linear-gradient(135deg,#1e3a5f,#2563eb)",fontFamily:"sans-serif"}}><div style={{background:"#fff",borderRadius:16,padding:40,width:380,boxShadow:"0 20px 60px rgba(0,0,0,.35)"}}>
    <div style={{textAlign:"center",marginBottom:24}}><div style={{fontSize:36}}>🏗️</div><h1 style={{margin:"8px 0 0",fontSize:22,color:"#1e3a5f"}}>Navacon Construction</h1><p style={{margin:"4px 0 0",fontSize:12,color:"#9ca3af"}}>Forecasting Platform</p></div>
    <div style={{marginBottom:10}}><label style={{fontSize:11,color:"#6b7280"}}>Email</label><input type="email" value={email} onChange={e=>{setEmail(e.target.value);setErr("");}} onKeyDown={e=>{if(e.key==="Enter")go();}} placeholder="you@navacon.com" style={{width:"100%",padding:"10px 14px",border:"1px solid #d1d5db",borderRadius:8,fontSize:13,boxSizing:"border-box",marginTop:4}}/></div>
    <div style={{marginBottom:8}}><label style={{fontSize:11,color:"#6b7280"}}>Password</label><input type="password" value={pw} onChange={e=>{setPw(e.target.value);setErr("");}} onKeyDown={e=>{if(e.key==="Enter")go();}} placeholder="Password" style={{width:"100%",padding:"10px 14px",border:"1px solid #d1d5db",borderRadius:8,fontSize:13,boxSizing:"border-box",marginTop:4}}/></div>
    {err&&<div style={{background:"#fef2f2",border:"1px solid #fecaca",borderRadius:6,padding:"8px",fontSize:12,color:"#dc2626",marginBottom:8}}>{err}</div>}
    <button onClick={go} style={{width:"100%",padding:12,background:"#2563eb",color:"#fff",border:"none",borderRadius:8,fontSize:14,fontWeight:700,cursor:"pointer",marginTop:4}}>Sign In</button>
    <div style={{textAlign:"center",marginTop:10}}><button onClick={()=>setSh(!sh)} style={{background:"none",border:"none",color:"#9ca3af",fontSize:11,cursor:"pointer",textDecoration:"underline"}}>{sh?"Hide":"Show credentials"}</button></div>
    {sh&&<div style={{marginTop:8,background:"#f9fafb",borderRadius:8,padding:10,border:"1px solid #e5e7eb",fontSize:10}}><table style={{width:"100%"}}><tbody>{users.map(u=><tr key={u.id}><td style={{padding:2}}><span style={{background:u.role==="admin"?"#fef3c7":"#dbeafe",color:u.role==="admin"?"#92400e":"#1e40af",padding:"1px 6px",borderRadius:8,fontSize:9,fontWeight:600}}>{u.role==="admin"?"Admin":"PM"}</span></td><td style={{padding:2,fontFamily:"monospace",color:"#2563eb"}}>{u.email}</td><td style={{padding:2,fontFamily:"monospace"}}>{u.pw}</td></tr>)}</tbody></table></div>}
  </div></div>;
}

function AdminDash({projects,onSelect,onToggleLock}){
  const[ck,setCk]=useState({});
  const allS=projects.map(p=>{const st=calcStats(p);let rd=0;const now=new Date();if(now<st.pE){let dd=new Date(now>st.pS?now:st.pS);while(dd<=st.pE){if(dd.getDay()%6)rd++;dd=AD(dd,1);}}return{...p,st:{...st,rd}};});
  const tV=allS.reduce((s,p)=>s+p.st.tpv,0);const tE=allS.reduce((s,p)=>s+p.st.el,0);const tF=allS.reduce((s,p)=>s+p.st.fu,0);const aP=allS.length?allS.reduce((s,p)=>s+p.st.op,0)/allS.length:0;
  const colors=["#2563eb","#16a34a","#f59e0b","#7c3aed","#dc2626","#0891b2","#db2777","#65a30d"];
  const ams=new Set();allS.forEach(p=>(p.st.am||[]).forEach(m=>ams.add(m)));const amo=[...ams].sort();
  const md=amo.map(m=>{const r={month:m,label:FL(m),total:0,projs:[],has:false};allS.forEach((p,pi)=>{const lk=!!(p.lm||{})[m];let rev=0;if(!lk){(p.sli||[]).forEach(sub=>{const t=(p.ti||[]).find(x=>x.id===sub.tiId);(p.act||[]).forEach(a=>{if(a.slId===sub.id&&a.mo===m)rev+=a.qty*(t?.rate||0);});});if(rev>0)r.has=true;}r.projs.push({name:p.name,rev:lk?0:rev,color:colors[pi%colors.length]});r.total+=lk?0:rev;});return r;}).filter(d=>d.has||d.total>0);
  const mxM=Math.max(...md.map(d=>d.total),1);const tFA=md.reduce((s,d)=>s+d.total,0);
  return <div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}>{[["Portfolio",$(tV),"#111"],["Earned",$(tE),"#16a34a"],["Forecast",$(tF),"#f59e0b"],["Avg %",PCT(aP),"#2563eb"]].map(([l,v,c])=><div key={l} style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:14,textAlign:"center"}}><div style={{fontSize:11,color:"#6b7280"}}>{l}</div><div style={{fontSize:22,fontWeight:700,color:c,marginTop:4}}>{v}</div></div>)}</div>
    <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:14,marginBottom:12}}><h4 style={{margin:"0 0 10px",fontSize:14}}>Projects</h4><div style={{overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#f9fafb"}}>{["Project","Manager","Value","Earned","Forecast","%","Days","🔒",""].map((h,i)=><th key={i} style={{padding:"6px 10px",textAlign:"left",fontWeight:600,color:"#6b7280",borderBottom:"1px solid #e5e7eb"}}>{h}</th>)}</tr></thead><tbody>{allS.map(p=>{const pc=p.st.op>=80?"#16a34a":p.st.op>=40?"#ca8a04":"#dc2626";return <tr key={p.id} style={{borderBottom:"1px solid #f3f4f6",background:p.locked?"#fefce8":"#fff"}}><td style={{padding:"6px 10px",fontWeight:600,color:"#2563eb",cursor:"pointer"}} onClick={()=>onSelect(p.id)}>{p.name}{p.locked&&" 🔒"}</td><td style={{padding:"6px 10px"}}>{p.mgr}</td><td style={{padding:"6px 10px",fontWeight:600}}>{$(p.st.tpv)}</td><td style={{padding:"6px 10px",color:"#16a34a"}}>{$(p.st.el)}</td><td style={{padding:"6px 10px",color:"#f59e0b"}}>{$(p.st.fu)}</td><td style={{padding:"6px 10px"}}><span style={{background:pc+"22",color:pc,padding:"2px 8px",borderRadius:12,fontSize:10,fontWeight:600}}>{PCT(p.st.op)}</span></td><td style={{padding:"6px 10px"}}>{p.st.rd}</td><td style={{padding:"6px 10px"}}><button onClick={()=>onToggleLock(p.id)} style={{background:p.locked?"#fef3c7":"#f3f4f6",color:p.locked?"#92400e":"#6b7280",border:"none",borderRadius:6,padding:"3px 8px",fontSize:11,fontWeight:600,cursor:"pointer"}}>{p.locked?"🔒":"🔓"}</button></td><td style={{padding:"6px 10px"}}><button onClick={()=>onSelect(p.id)} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"3px 10px",fontSize:11,fontWeight:600,cursor:"pointer"}}>Open</button></td></tr>;})}</tbody></table></div></div>
    <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><h4 style={{margin:0,fontSize:14}}>Monthly Forecast</h4><div style={{background:"#f0fdf4",border:"1px solid #bbf7d0",borderRadius:8,padding:"4px 12px"}}><span style={{fontSize:11,color:"#6b7280"}}>Total: </span><span style={{fontSize:16,fontWeight:700,color:"#16a34a"}}>{$(tFA)}</span></div></div>
      <div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:10,justifyContent:"center"}}>{allS.map((p,pi)=><div key={p.id} style={{display:"flex",alignItems:"center",gap:3}}><div style={{width:8,height:8,borderRadius:2,background:colors[pi%colors.length]}}/><span style={{fontSize:9}}>{p.name}</span></div>)}</div>
      {md.length===0?<div style={{textAlign:"center",color:"#9ca3af",padding:20}}>No forecast data</div>:<div style={{paddingLeft:50,paddingBottom:40}}><div style={{position:"relative",height:200,borderLeft:"2px solid #d1d5db",borderBottom:"2px solid #d1d5db"}}>{[.25,.5,.75,1].map((t,i)=><div key={i} style={{position:"absolute",left:0,right:0,bottom:`${t*100}%`,borderTop:"1px dashed #e5e7eb"}}><span style={{position:"absolute",right:"100%",marginRight:6,top:-7,fontSize:9,color:"#9ca3af"}}>{$(Math.round(mxM*t))}</span></div>)}<div style={{display:"flex",alignItems:"flex-end",height:"100%",gap:2,padding:"0 4px"}}>{md.map((m,mi)=>{const h=mxM>0?(m.total/mxM)*100:0;return <div key={mi} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-end",height:"100%"}}>{m.total>0&&<div style={{fontSize:7,fontWeight:700,marginBottom:1}}>{$(m.total)}</div>}<div style={{width:"70%",maxWidth:40,height:`${Math.max(h,2)}%`,borderRadius:"3px 3px 0 0",minHeight:3,display:"flex",flexDirection:"column-reverse",overflow:"hidden"}}>{m.projs.map((pr,pi)=>pr.rev>0?<div key={pi} style={{width:"100%",height:`${(pr.rev/m.total)*100}%`,background:pr.color,minHeight:2}}/>:null)}</div></div>;})}</div></div><div style={{display:"flex",gap:2,paddingLeft:4,marginTop:4}}>{md.map((m,i)=><div key={i} style={{flex:1,textAlign:"center"}}><span style={{fontSize:7,color:"#6b7280",transform:"rotate(-50deg)",transformOrigin:"top center",display:"inline-block",whiteSpace:"nowrap"}}>{m.label}</span></div>)}</div></div>}
    </div>
  </div>;
}

export default function App(){
  const[projects,setProjects]=useState(null);
  const[selId,setSelId]=useState(null);
  const[loading,setLoading]=useState(true);
  const[curUser,setCurUser]=useState(null);
  const[users]=useState(USERS);
  const[showNew,setShowNew]=useState(false);
  const[nn,setNn]=useState("");
  const[nm,setNm]=useState("");
  const[cr,setCr]=useState(false);

  const defs=[mkSample("Metro Tower","John Smith",0,1),mkSample("Riverside Plaza","Lisa Chen",2,0.8),mkSample("Harbor Bridge","Ahmed Khan",1,1.5),mkSample("Airport Terminal","Lisa Chen",0,2),mkSample("City Hospital","Ahmed Khan",3,1.2)];

  useEffect(()=>{(async()=>{try{const{data}=await supabase.from('projects').select('*').order('created_at');if(data&&data.length>0){setProjects(data.map(r=>{const dd=r.data||{};return{id:r.id,name:r.name,mgr:r.manager_name,locked:r.locked||false,li:dd.li||[],ti:dd.ti||[],sli:dd.sli||[],act:dd.act||[],lm:dd.lm||{}};}));}else{setProjects(defs);for(const p of defs){await supabase.from('projects').insert({id:p.id,name:p.name,manager_name:p.mgr,locked:false,data:{li:p.li,ti:p.ti,sli:p.sli,act:p.act,lm:p.lm}}).catch(()=>{});}}}catch(e){console.error(e);setProjects(defs);}setLoading(false);})();},[]);

  useEffect(()=>{if(!projects||loading)return;const s=async()=>{for(const p of projects){try{await supabase.from('projects').upsert({id:p.id,name:p.name,manager_name:p.mgr,locked:p.locked||false,data:{li:p.li,ti:p.ti,sli:p.sli,act:p.act,lm:p.lm}});}catch{}}};const t=setTimeout(s,1000);return()=>clearTimeout(t);},[projects,loading]);

  if(loading||!projects)return <div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"sans-serif"}}><div style={{textAlign:"center"}}><div style={{fontSize:28}}>⏳</div><div style={{color:"#6b7280"}}>Loading...</div></div></div>;
  if(!curUser)return <LoginScreen users={users} onLogin={setCurUser}/>;

  const user=users.find(u=>u.id===curUser);
  const isAdmin=user?.role==="admin";
  const myP=isAdmin?projects:projects.filter(p=>p.mgr===user?.name);
  const sel=projects.find(p=>p.id===selId);
  const up=u=>setProjects(projects.map(p=>p.id===u.id?u:p));
  const del=async id=>{const p=projects.find(x=>x.id===id);if(p?.locked)return;try{await supabase.from('projects').delete().eq('id',id);}catch{}setProjects(projects.filter(p=>p.id!==id));setSelId(null);};
  const tl=id=>setProjects(projects.map(p=>p.id===id?{...p,locked:!p.locked}:p));

  if(selId&&sel)return <div style={{fontFamily:"sans-serif",background:"#f8fafc",minHeight:"100vh"}}><ProjectView proj={sel} setProj={up} onBack={()=>setSelId(null)} onDelete={()=>del(sel.id)}/></div>;

  return <div style={{fontFamily:"sans-serif",background:"#f8fafc",minHeight:"100vh"}}>
    <div style={{background:"linear-gradient(135deg,#1e3a5f,#2563eb)",color:"#fff",padding:"16px 24px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h1 style={{margin:0,fontSize:20,fontWeight:700}}>Navacon Construction</h1><div style={{fontSize:11,opacity:.8}}>{isAdmin?"Admin":"Projects"} · {user?.name}</div></div><div style={{display:"flex",gap:8}}><button onClick={()=>{setNn("");setNm("");setShowNew(true);}} style={{background:"rgba(255,255,255,.2)",color:"#fff",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>+ New</button>{cr?<div style={{display:"flex",gap:4,alignItems:"center"}}><span style={{fontSize:11,color:"#fca5a5"}}>Reset?</span><button onClick={async()=>{for(const p of projects.filter(p=>!p.locked)){try{await supabase.from('projects').delete().eq('id',p.id);}catch{}}const nd=defs.map(d=>({...d,id:uid()}));for(const p of nd){try{await supabase.from('projects').insert({id:p.id,name:p.name,manager_name:p.mgr,locked:false,data:{li:p.li,ti:p.ti,sli:p.sli,act:p.act,lm:p.lm}});}catch{}}setProjects([...projects.filter(p=>p.locked),...nd]);setCr(false);}} style={{background:"#dc2626",color:"#fff",border:"none",borderRadius:6,padding:"4px 10px",fontSize:11,fontWeight:600,cursor:"pointer"}}>Yes</button><button onClick={()=>setCr(false)} style={{background:"rgba(255,255,255,.2)",color:"#fff",border:"none",borderRadius:6,padding:"4px 10px",fontSize:11,fontWeight:600,cursor:"pointer"}}>No</button></div>:<button onClick={()=>setCr(true)} style={{background:"rgba(255,255,255,.1)",color:"#fff",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>↺ Reset</button>}<button onClick={()=>{setCurUser(null);setSelId(null);}} style={{background:"rgba(255,255,255,.15)",color:"#fff",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Logout</button></div></div></div>
    <div style={{padding:"16px 24px",maxWidth:1200,margin:"0 auto"}}>{isAdmin?<AdminDash projects={projects} onSelect={setSelId} onToggleLock={tl}/>:
      <div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}>{[["Projects",myP.length,"#2563eb"],["Value",$(myP.reduce((s,p)=>s+calcStats(p).tpv,0)),"#111"],["Earned",$(myP.reduce((s,p)=>s+calcStats(p).el,0)),"#16a34a"],["Forecast",$(myP.reduce((s,p)=>s+calcStats(p).fu,0)),"#f59e0b"]].map(([l,v,c])=><div key={l} style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:14,textAlign:"center"}}><div style={{fontSize:11,color:"#6b7280"}}>{l}</div><div style={{fontSize:20,fontWeight:700,color:c,marginTop:4}}>{v}</div></div>)}</div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300,1fr))",gap:12}}>{myP.map(p=>{const st=calcStats(p);const pc=st.op>=80?"#16a34a":st.op>=40?"#ca8a04":"#dc2626";return <div key={p.id} onClick={()=>setSelId(p.id)} style={{background:"#fff",borderRadius:12,border:"1px solid #e5e7eb",padding:18,cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><div style={{fontSize:15,fontWeight:700,color:"#1e3a5f"}}>{p.name}{p.locked&&" 🔒"}</div><span style={{background:pc+"22",color:pc,padding:"2px 8px",borderRadius:12,fontSize:11,fontWeight:600}}>{PCT(st.op)}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{[["Value",$(st.tpv),"#111"],["Earned",$(st.el),"#16a34a"],["Forecast",$(st.fu),"#f59e0b"]].map(([l,v,c])=><div key={l}><div style={{fontSize:9,color:"#6b7280"}}>{l}</div><div style={{fontSize:14,fontWeight:700,color:c}}>{v}</div></div>)}</div><div style={{marginTop:8,height:6,background:"#e5e7eb",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${Math.min(st.op,100)}%`,background:"#2563eb",borderRadius:3}}/></div></div>;})}</div></div>}
    </div>
    {showNew&&<div style={{position:"fixed",inset:0,zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.5)"}} onClick={()=>setShowNew(false)}><div style={{background:"#fff",borderRadius:12,padding:24,maxWidth:400,width:"90%"}} onClick={e=>e.stopPropagation()}><h3 style={{margin:"0 0 16px"}}>New Project</h3><div style={{marginBottom:8}}><label style={{fontSize:11,color:"#6b7280"}}>Name</label><input value={nn} onChange={e=>setNn(e.target.value)} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box",marginTop:4}}/></div>{isAdmin&&<div style={{marginBottom:8}}><label style={{fontSize:11,color:"#6b7280"}}>Manager</label><select value={nm} onChange={e=>setNm(e.target.value)} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box",background:"#fff",marginTop:4}}><option value="">Select...</option>{users.filter(u=>u.role==="pm").map(u=><option key={u.id} value={u.name}>{u.name}</option>)}</select></div>}<div style={{display:"flex",gap:8,marginTop:12}}><button onClick={async()=>{if(!nn.trim())return;const np={id:uid(),name:nn.trim(),mgr:isAdmin?(nm||user.name):user.name,li:[],ti:[],sli:[],act:[],lm:{},locked:false};try{await supabase.from('projects').insert({id:np.id,name:np.name,manager_name:np.mgr,locked:false,data:{}});}catch{}setProjects([...projects,np]);setShowNew(false);}} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Create</button><button onClick={()=>setShowNew(false)} style={{background:"#f3f4f6",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Cancel</button></div></div></div>}
  </div>;
}