import { useState, useMemo, useRef } from "react";
import { uid, P, F, AD, FM, FL, GM, $, PCT, parseCSV, normS, normB, mapCSV, calcStats } from './helpers';

export default function ProjectView({proj,setProj,onBack,onDelete}){
  const d=proj;
  const[tab,setTab]=useState("Dashboard");
  const[modal,setModal]=useState(null);
  const[form,setForm]=useState({});
  const[impText,setImpText]=useState("");
  const[impPreview,setImpPreview]=useState(null);
  const[impMode,setImpMode]=useState("replace");
  const[editAllocId,setEditAllocId]=useState(null);
  const[editAllocQty,setEditAllocQty]=useState(0);
  const[confirmDel,setConfirmDel]=useState(false);
  const fileRef=useRef();
  const stats=useMemo(()=>calcStats(d),[d]);
  const lp=lid=>{const subs=d.sli.filter(x=>x.liId===lid);if(!subs.length)return 0;let tv=0,ev=0;subs.forEach(sub=>{const t=d.ti.find(x=>x.id===sub.tiId);const r=t?.rate||0;tv+=sub.alloc*r;d.act.forEach(a=>{if(a.slId===sub.id)ev+=a.qty*r;});});return tv>0?(ev/tv)*100:0;};
  const ts=t=>({padding:"10px 16px",fontSize:12,fontWeight:tab===t?700:500,color:tab===t?"#2563eb":"#6b7280",background:"none",border:"none",borderBottom:tab===t?"2px solid #2563eb":"2px solid transparent",cursor:"pointer",marginBottom:-2,whiteSpace:"nowrap"});

  const Dash=()=>{
    const bars=stats.am.map(m=>{let rev=0;d.sli.forEach(s=>{const t=d.ti.find(x=>x.id===s.tiId);d.act.forEach(a=>{if(a.slId===s.id&&a.mo===m)rev+=a.qty*(t?.rate||0);});});return{m,rev,lk:!!d.lm[m]};});
    const mx=Math.max(...bars.map(b=>b.rev),1);const has=bars.some(b=>b.rev>0);
    const now=new Date();const td2=Math.max(Math.round((stats.pE-stats.pS)/864e5),1);const el=Math.round((now-stats.pS)/864e5);const pe=Math.min(100,Math.max(0,(el/td2)*100));const spi=pe>0?stats.op/pe:1;
    const sc=spi>=1?"#16a34a":spi>=0.9?"#2563eb":spi>=0.75?"#ca8a04":"#dc2626";
    const sl=spi>=1?"Ahead":spi>=0.9?"On Track":spi>=0.75?"Warning":"Critical";
    let rd=0;if(now<stats.pE){let dd=new Date(now>stats.pS?now:stats.pS);while(dd<=stats.pE){if(dd.getDay()%6)rd++;dd=AD(dd,1);}}
    return <div>
      <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:14,marginBottom:12}}><div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:12}}>
        {[["Value",$(stats.tpv),"#111"],["Earned",$(stats.el),"#16a34a"],["Forecast",$(stats.fu),"#f59e0b"],["Progress",PCT(stats.op),"#2563eb"],["Days Left",String(rd),"#7c3aed"],["SPI",spi.toFixed(2),sc]].map(([l,v,c],i)=><div key={i} style={{textAlign:"center"}}><div style={{fontSize:11,color:"#6b7280"}}>{l}</div><div style={{fontSize:18,fontWeight:700,color:c,marginTop:2}}>{v}</div>{l==="SPI"&&<span style={{background:sc+"22",color:sc,padding:"2px 8px",borderRadius:12,fontSize:10,fontWeight:600}}>{sl}</span>}</div>)}
      </div></div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
        <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:16}}><h4 style={{margin:"0 0 8px",fontSize:13}}>Revenue</h4>{!has?<div style={{textAlign:"center",color:"#9ca3af",padding:20}}>No data</div>:<div><div style={{display:"flex",alignItems:"flex-end",gap:2,height:150,borderBottom:"2px solid #e5e7eb"}}>{bars.map(b=><div key={b.m} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-end",height:"100%"}}>{b.rev>0&&<div style={{fontSize:7,fontWeight:600,marginBottom:1}}>{$(b.rev)}</div>}<div style={{width:"65%",height:`${Math.max((b.rev/mx)*100,b.rev>0?2:0)}%`,background:b.lk?"#2563eb":"#f59e0b",borderRadius:"3px 3px 0 0",minHeight:b.rev>0?2:0}}/></div>)}</div><div style={{display:"flex",gap:1,marginTop:2}}>{bars.map(b=><div key={b.m} style={{flex:1,textAlign:"center",fontSize:7,color:"#9ca3af"}}>{FL(b.m)}</div>)}</div></div>}</div>
        <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:16}}><h4 style={{margin:"0 0 12px",fontSize:13}}>Progress</h4>{d.li.length?d.li.map(l=>{const p=lp(l.id);return <div key={l.id} style={{display:"flex",alignItems:"center",gap:6,marginBottom:8}}><span style={{fontSize:11,width:120,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>#{l.rn} {l.desc}</span><div style={{flex:1,height:8,background:"#e5e7eb",borderRadius:4,overflow:"hidden"}}><div style={{height:"100%",width:`${Math.min(p,100)}%`,background:p>=80?"#16a34a":"#2563eb",borderRadius:4}}/></div><span style={{fontSize:10,fontWeight:600,minWidth:40,textAlign:"right"}}>{PCT(p)}</span></div>;}):(<div style={{textAlign:"center",color:"#9ca3af",padding:20}}>No activities</div>)}</div>
      </div>
    </div>;
  };

  const Sched=()=>{
    const gm=stats.am;const sorted=[...d.li].sort((a,b)=>(P(a.sd)||new Date(9999,0))-(P(b.sd)||new Date(9999,0)));
    return <div>
      <div style={{marginBottom:12,display:"flex",gap:8}}><button onClick={()=>{setForm({desc:"",sd:"",ed:""});setModal("addLine");}} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>+ Add</button><button onClick={()=>{setImpText("");setImpPreview(null);setModal("importSched");}} style={{background:"#f3f4f6",color:"#374151",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>📄 Import</button></div>
      <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:12,overflow:"auto"}}>{gm.length===0?<div style={{textAlign:"center",color:"#9ca3af",padding:30}}>Add activities</div>:<div style={{minWidth:Math.max(600,gm.length*70+340)}}><div style={{display:"grid",gridTemplateColumns:`180px 80px 80px repeat(${gm.length},1fr)`,borderBottom:"1px solid #e5e7eb"}}><div style={{padding:"6px 10px",fontSize:11,fontWeight:600,color:"#6b7280",background:"#f9fafb"}}>Activity</div><div style={{padding:6,fontSize:11,fontWeight:600,color:"#6b7280",background:"#f9fafb",textAlign:"center"}}>Start</div><div style={{padding:6,fontSize:11,fontWeight:600,color:"#6b7280",background:"#f9fafb",textAlign:"center"}}>End</div>{gm.map(m=><div key={m} style={{padding:"6px 4px",fontSize:9,fontWeight:600,color:"#6b7280",textAlign:"center",background:"#f9fafb",borderLeft:"1px solid #f0f0f0"}}>{FL(m)}</div>)}</div>
        {sorted.map(l=>{const sd=P(l.sd),ed=P(l.ed),p=lp(l.id);return <div key={l.id} style={{display:"grid",gridTemplateColumns:`180px 80px 80px repeat(${gm.length},1fr)`,borderBottom:"1px solid #f3f4f6",alignItems:"center"}}><div style={{padding:"6px 10px",display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:10,color:"#9ca3af"}}>{l.rn}</span><span style={{fontSize:12,fontWeight:500,flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{l.desc}</span><button onClick={()=>{setForm({...l});setModal("editLine");}} style={{background:"none",border:"none",cursor:"pointer",fontSize:11,padding:0}}>✏️</button><button onClick={()=>setProj({...d,li:d.li.filter(x=>x.id!==l.id),sli:d.sli.filter(x=>x.liId!==l.id)})} style={{background:"none",border:"none",cursor:"pointer",fontSize:11,color:"#dc2626",padding:0}}>🗑</button></div><div style={{textAlign:"center",fontSize:10}}>{l.sd}</div><div style={{textAlign:"center",fontSize:10}}>{l.ed}</div>{gm.map(m=>{const[y,mo]=m.split("-").map(Number);const ms=new Date(y,mo-1,1),me=new Date(y,mo,0);const inR=sd&&ed&&me>=sd&&ms<=ed;return <div key={m} style={{padding:"3px 1px",borderLeft:"1px solid #f0f0f0",height:28,display:"flex",alignItems:"center"}}>{inR&&<div style={{width:"100%",height:18,borderRadius:4,background:"#bfdbfe",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:0,top:0,bottom:0,width:`${Math.min(p,100)}%`,background:"#2563eb",borderRadius:4}}/></div>}</div>;})}</div>;})}
      </div>}</div>
    </div>;
  };

  const Res=()=><div>
    <div style={{display:"flex",gap:8,marginBottom:12}}><button onClick={()=>{setForm({code:"",desc:"",unit:"m²",qty:"",rate:""});setModal("addTender");}} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>+ Tender</button><button onClick={()=>{setImpText("");setImpPreview(null);setModal("importBOQ");}} style={{background:"#f3f4f6",color:"#374151",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>📄 Import</button><button onClick={()=>{setForm({liId:"",tiId:"",alloc:""});setModal("linkRes");}} style={{background:"#f3f4f6",color:"#374151",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>+ Link</button></div>
    <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:12,marginBottom:12}}><h4 style={{margin:"0 0 10px",fontSize:13}}>BOQ</h4><div style={{overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#f9fafb"}}>{["Code","Desc","Unit","Qty","Rate","Value","Alloc",""].map((h,i)=><th key={i} style={{padding:"6px 8px",textAlign:"left",fontWeight:600,color:"#6b7280",borderBottom:"1px solid #e5e7eb"}}>{h}</th>)}</tr></thead><tbody>{d.ti.map(t=>{let al=0;d.sli.forEach(s=>{if(s.tiId===t.id)al+=s.alloc;});return <tr key={t.id} style={{borderBottom:"1px solid #f3f4f6"}}><td style={{padding:"6px 8px",fontWeight:600,color:"#2563eb"}}>{t.code}</td><td style={{padding:"6px 8px"}}>{t.desc}</td><td style={{padding:"6px 8px"}}>{t.unit}</td><td style={{padding:"6px 8px"}}>{t.qty.toLocaleString()}</td><td style={{padding:"6px 8px"}}>{$(t.rate)}</td><td style={{padding:"6px 8px",fontWeight:600}}>{$(t.qty*t.rate)}</td><td style={{padding:"6px 8px"}}>{al.toLocaleString()}/{t.qty.toLocaleString()}</td><td style={{padding:"6px 8px"}}><div style={{display:"flex",gap:4}}><button onClick={()=>{setForm({...t});setModal("editTender");}} style={{background:"#f3f4f6",border:"none",borderRadius:4,padding:"2px 8px",fontSize:11,cursor:"pointer"}}>Edit</button><button onClick={()=>setProj({...d,ti:d.ti.filter(x=>x.id!==t.id),sli:d.sli.filter(x=>x.tiId!==t.id)})} style={{background:"#fee2e2",color:"#dc2626",border:"none",borderRadius:4,padding:"2px 8px",fontSize:11,cursor:"pointer"}}>Del</button></div></td></tr>;})}</tbody></table></div></div>
    <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:12}}><h4 style={{margin:"0 0 10px",fontSize:13}}>Allocations</h4>{d.li.map(l=>{const subs=d.sli.filter(x=>x.liId===l.id);return <div key={l.id} style={{marginBottom:12}}><div style={{fontSize:12,fontWeight:600,marginBottom:4}}>#{l.rn} {l.desc}</div>{!subs.length?<div style={{fontSize:11,color:"#9ca3af",paddingLeft:8}}>None</div>:<table style={{width:"100%",borderCollapse:"collapse",fontSize:11,marginLeft:8}}><tbody>{subs.map(sub=>{const tn=d.ti.find(x=>x.id===sub.tiId);const r=tn?.rate||0;let ta=0;d.act.forEach(a=>{if(a.slId===sub.id)ta+=a.qty;});const pv=sub.alloc>0?(ta/sub.alloc)*100:0;const pc=pv>=80?"#16a34a":pv>=40?"#ca8a04":"#dc2626";const isEd=editAllocId===sub.id;return <tr key={sub.id} style={{borderBottom:"1px solid #f3f4f6"}}><td style={{padding:"4px 8px"}}>{tn?.code} — {tn?.desc}</td><td style={{padding:"4px 8px"}}>{isEd?<span style={{display:"flex",gap:3}}><input type="number" value={editAllocQty} onChange={e=>setEditAllocQty(e.target.value)} style={{width:70,padding:"2px 6px",border:"1px solid #93c5fd",borderRadius:4,fontSize:11}}/><button onClick={()=>{setProj({...d,sli:d.sli.map(x=>x.id===sub.id?{...x,alloc:Number(editAllocQty)}:x)});setEditAllocId(null);}} style={{background:"#dcfce7",color:"#16a34a",border:"none",borderRadius:4,padding:"2px 6px",fontSize:10,cursor:"pointer"}}>✓</button></span>:<span onClick={()=>{setEditAllocId(sub.id);setEditAllocQty(sub.alloc);}} style={{cursor:"pointer",color:"#2563eb",borderBottom:"1px dashed #93c5fd"}}>{sub.alloc.toLocaleString()}</span>}</td><td style={{padding:"4px 8px",color:"#16a34a",fontWeight:600}}>{$(ta*r)}</td><td style={{padding:"4px 8px"}}><span style={{background:pc+"22",color:pc,padding:"2px 8px",borderRadius:12,fontSize:10,fontWeight:600}}>{PCT(pv)}</span></td><td><button onClick={()=>setProj({...d,sli:d.sli.filter(x=>x.id!==sub.id),act:d.act.filter(a=>a.slId!==sub.id)})} style={{background:"none",border:"none",color:"#dc2626",cursor:"pointer",fontSize:10}}>✕</button></td></tr>;})}</tbody></table>}</div>;})}</div>
  </div>;

  const Track=()=>{
    const cm=FM(new Date());const allSubs=d.sli.map(sub=>{const tn=d.ti.find(t=>t.id===sub.tiId);const la=d.li.find(l=>l.id===sub.liId);let ta=0;d.act.forEach(a=>{if(a.slId===sub.id)ta+=a.qty;});return{...sub,tn,la,ta,rem:sub.alloc-ta};});
    if(!allSubs.length)return <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:40,textAlign:"center",color:"#9ca3af"}}>Link resources first</div>;
    const saveAct=(slId,mo,qty)=>{const ex=d.act.find(a=>a.slId===slId&&a.mo===mo);if(ex)setProj({...d,act:d.act.map(a=>a.id===ex.id?{...a,qty:Number(qty)}:a)});else setProj({...d,act:[...d.act,{id:uid(),slId,mo,qty:Number(qty)}]});};
    const toggleLk=m=>{const lm={...d.lm};if(lm[m])delete lm[m];else lm[m]=true;setProj({...d,lm});};
    return <div>
      <div style={{display:"flex",gap:8,marginBottom:12}}><button onClick={()=>{const lm={...d.lm};stats.am.forEach(m=>{if(m<cm)lm[m]=true;});setProj({...d,lm});}} style={{background:"#fee2e2",color:"#dc2626",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>🔒 Lock Past</button><button onClick={()=>setProj({...d,lm:{}})} style={{background:"#dcfce7",color:"#16a34a",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>🔓 Unlock</button></div>
      <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:8,overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11,minWidth:stats.am.length*58+250}}><thead><tr style={{background:"#f9fafb"}}><th style={{padding:"4px 6px",textAlign:"left",fontWeight:600,color:"#6b7280",borderBottom:"2px solid #e5e7eb",position:"sticky",left:0,background:"#f9fafb",minWidth:120,zIndex:2}}>Resource</th><th style={{padding:4,textAlign:"center",fontWeight:600,borderBottom:"2px solid #e5e7eb",minWidth:48,background:"#f3f4f6"}}>Alloc</th>{stats.am.map(m=>{const lk=!!d.lm[m];return <th key={m} style={{padding:"2px 1px",textAlign:"center",fontWeight:600,fontSize:8,borderBottom:"2px solid #e5e7eb",minWidth:54,color:lk?"#dc2626":"#6b7280",background:lk?"#fef2f2":"#f9fafb"}}><button onClick={()=>toggleLk(m)} style={{background:"none",border:"none",cursor:"pointer",fontSize:9,display:"block",margin:"0 auto"}}>{lk?"🔒":"🔓"}</button>{FL(m)}</th>;})}<th style={{padding:4,textAlign:"center",fontWeight:600,color:"#2563eb",borderBottom:"2px solid #e5e7eb",minWidth:48,background:"#eff6ff"}}>Done</th><th style={{padding:4,textAlign:"center",fontWeight:600,color:"#dc2626",borderBottom:"2px solid #e5e7eb",minWidth:48,background:"#fef2f2"}}>Rem</th></tr></thead>
        <tbody>{allSubs.map(sub=><tr key={sub.id} style={{borderBottom:"1px solid #f3f4f6"}}><td style={{padding:"4px 6px",position:"sticky",left:0,background:"#fff",zIndex:1,borderRight:"1px solid #e5e7eb"}}><div style={{fontSize:10,fontWeight:600}}>{sub.tn?.code} — {sub.tn?.desc}</div><div style={{fontSize:8,color:"#9ca3af"}}>{sub.la?.desc}</div></td><td style={{padding:3,textAlign:"center",fontWeight:700,background:"#f3f4f6"}}>{sub.alloc.toLocaleString()}</td>{stats.am.map(m=>{const lk=!!d.lm[m];const a=d.act.find(x=>x.slId===sub.id&&x.mo===m);const val=a?.qty??"";return <td key={m} style={{padding:1,textAlign:"center",background:lk?"#fef2f2":"#fff"}}>{lk?<div style={{padding:3,fontSize:10,fontWeight:val?600:400,color:val?"#374151":"#d1d5db"}}>{val||"—"}</div>:<input type="number" defaultValue={val} placeholder="0" key={sub.id+m+String(val)} onBlur={e=>{const v=e.target.value;if(String(v)!==String(val??""))saveAct(sub.id,m,v);}} onKeyDown={e=>{if(e.key==="Enter")e.target.blur();}} style={{width:"100%",padding:"3px 1px",border:"1px solid #e5e7eb",borderRadius:3,fontSize:10,textAlign:"center",boxSizing:"border-box"}}/>}</td>;})}<td style={{padding:3,textAlign:"center",fontWeight:700,color:"#2563eb",background:"#eff6ff"}}>{sub.ta.toLocaleString()}</td><td style={{padding:3,textAlign:"center",fontWeight:700,color:sub.rem<=0?"#16a34a":"#dc2626",background:"#fef2f2"}}>{sub.rem.toLocaleString()}</td></tr>)}
        <tr style={{background:"#f0fdf4",borderTop:"2px solid #d1d5db"}}><td style={{padding:6,fontWeight:700,fontSize:10,position:"sticky",left:0,background:"#f0fdf4",zIndex:1}}>REVENUE</td><td style={{padding:3,textAlign:"center",fontWeight:700,fontSize:9,background:"#f0fdf4",color:"#16a34a"}}>{$(allSubs.reduce((s,x)=>s+x.alloc*(x.tn?.rate||0),0))}</td>{stats.am.map(m=>{let mR=0;allSubs.forEach(sub=>{const a=d.act.find(x=>x.slId===sub.id&&x.mo===m);mR+=(a?.qty||0)*(sub.tn?.rate||0);});return <td key={m} style={{padding:3,textAlign:"center",fontSize:8,fontWeight:700,color:mR>0?"#16a34a":"#d1d5db"}}>{mR>0?$(mR):"—"}</td>;})}<td style={{padding:3,textAlign:"center",fontWeight:700,color:"#16a34a",background:"#dcfce7"}}>{$(allSubs.reduce((s,x)=>s+x.ta*(x.tn?.rate||0),0))}</td><td style={{padding:3,textAlign:"center",fontWeight:700,color:"#dc2626",background:"#fef2f2"}}>{$(allSubs.reduce((s,x)=>s+x.rem*(x.tn?.rate||0),0))}</td></tr></tbody></table></div>
    </div>;
  };

  const Forecast=()=>{
    const lockedMs=stats.am.filter(m=>d.lm[m]);const openMs=stats.am.filter(m=>!d.lm[m]);
    const pd2=d.sli.map(sub=>{const tn=d.ti.find(t=>t.id===sub.tiId);const la=d.li.find(l=>l.id===sub.liId);const mo=lockedMs.map(m=>{let q=0;d.act.forEach(a=>{if(a.slId===sub.id&&a.mo===m)q+=a.qty;});return q;}).filter(q=>q>0);const avg=mo.length?mo.reduce((a,b)=>a+b,0)/mo.length:0;let ta=0;d.act.forEach(a=>{if(a.slId===sub.id)ta+=a.qty;});const rem=Math.max(0,sub.alloc-ta);return{sub,tn,la,avg,ta,rem,mLeft:avg>0?Math.ceil(rem/avg):null};});
    const mr=stats.am.map(m=>{let aR=0,fR=0,pR=0;d.sli.forEach(sub=>{const tn=d.ti.find(t=>t.id===sub.tiId);const r=tn?.rate||0;let aq=0;d.act.forEach(a=>{if(a.slId===sub.id&&a.mo===m)aq+=a.qty;});if(d.lm[m])aR+=aq*r;else{fR+=aq*r;const p=pd2.find(p=>p.sub.id===sub.id);pR+=(p?.avg||0)*r;}});return{month:m,label:FL(m),locked:!!d.lm[m],aR,fR,pR};});
    const tFC=mr.reduce((s,m)=>s+m.fR,0);const tPr=mr.reduce((s,m)=>s+m.pR,0);
    return <div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}>{[["Contract",$(stats.tpv),"#111",null],["Earned",$(stats.el),"#16a34a",null],["Forecast",$(tFC),"#f59e0b","Gap: "+$(stats.tpv-stats.el-tFC)],["Projected",$(tPr),"#7c3aed","Gap: "+$(stats.tpv-stats.el-tPr)]].map(([l,v,c,sub])=><div key={l} style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:14,textAlign:"center"}}><div style={{fontSize:11,color:"#6b7280"}}>{l}</div><div style={{fontSize:20,fontWeight:700,color:c,marginTop:4}}>{v}</div>{sub&&<div style={{fontSize:10,color:"#9ca3af",marginTop:2}}>{sub}</div>}</div>)}</div>
      <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:12,marginBottom:12}}><h4 style={{margin:"0 0 10px",fontSize:13}}>Productivity</h4>{!pd2.length?<div style={{textAlign:"center",color:"#9ca3af",padding:20}}>Link resources</div>:<div style={{overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:"#f9fafb"}}>{["Resource","Alloc","Done","Rem","Avg/Mo","Months","Status"].map((h,i)=><th key={i} style={{padding:"6px 8px",textAlign:"left",fontWeight:600,color:"#6b7280",borderBottom:"1px solid #e5e7eb"}}>{h}</th>)}</tr></thead><tbody>{pd2.map(p=>{const ok=p.mLeft!==null&&p.mLeft<=openMs.length;const c2=p.mLeft===null?"#9ca3af":ok?"#16a34a":"#dc2626";return <tr key={p.sub.id} style={{borderBottom:"1px solid #f3f4f6"}}><td style={{padding:"6px 8px"}}><b>{p.tn?.code}</b> {p.tn?.desc}</td><td style={{padding:"6px 8px"}}>{p.sub.alloc.toLocaleString()}</td><td style={{padding:"6px 8px",color:"#2563eb",fontWeight:600}}>{p.ta.toLocaleString()}</td><td style={{padding:"6px 8px",color:"#dc2626",fontWeight:600}}>{p.rem.toLocaleString()}</td><td style={{padding:"6px 8px",fontWeight:600}}>{p.avg>0?Math.round(p.avg).toLocaleString():"—"}</td><td style={{padding:"6px 8px",fontWeight:600,color:c2}}>{p.mLeft??'—'}</td><td style={{padding:"6px 8px"}}><span style={{background:c2+"22",color:c2,padding:"2px 8px",borderRadius:12,fontSize:10,fontWeight:600}}>{p.mLeft===null?"No Data":ok?"On Track":"At Risk"}</span></td></tr>;})}</tbody></table></div>}</div>
    </div>;
  };

  const Reports=()=>{
    const sm=stats.am.map(m=>{let rev=0;d.sli.forEach(sub=>{const t=d.ti.find(x=>x.id===sub.tiId);d.act.forEach(a=>{if(a.slId===sub.id&&a.mo===m)rev+=a.qty*(t?.rate||0);});});return{month:m,label:FL(m),actual:d.lm[m]?rev:0,forecast:d.lm[m]?0:rev};});
    const tA=sm.reduce((s,r)=>s+r.actual,0);const tF=sm.reduce((s,r)=>s+r.forecast,0);const delta=stats.tpv-(tA+tF);
    const ls=d.li.map(l=>{const subs=d.sli.filter(x=>x.liId===l.id);let tv=0,ev=0;subs.forEach(sub=>{const t=d.ti.find(x=>x.id===sub.tiId);const r=t?.rate||0;tv+=sub.alloc*r;d.act.forEach(a=>{if(a.slId===sub.id)ev+=a.qty*r;});});return{...l,tv,ev,pct:tv>0?(ev/tv)*100:0};});
    const dlCSV=()=>{const r=["Month,Actual,Forecast"];sm.forEach(x=>{r.push(`"${x.label}",${x.actual},${x.forecast}`);});r.push("");r.push("Activity,Progress,Value,Earned,Outstanding");ls.forEach(l=>{r.push(`"${l.desc}",${l.pct.toFixed(1)},${l.tv},${l.ev},${l.tv-l.ev}`);});const b=new Blob([r.join("\n")],{type:"text/csv"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=d.name+"_Report.csv";document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u);};
    return <div>
      <div style={{display:"flex",justifyContent:"flex-end",marginBottom:12}}><button onClick={dlCSV} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer"}}>📥 Export CSV</button></div>
      <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:12,marginBottom:12}}><h4 style={{margin:"0 0 10px",fontSize:13}}>Monthly Summary</h4><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#f9fafb"}}>{["Month","Actual","Forecast"].map((h,i)=><th key={i} style={{padding:"6px 10px",textAlign:"right",fontWeight:600,color:"#6b7280",borderBottom:"1px solid #e5e7eb"}}>{h}</th>)}</tr></thead><tbody>{sm.map(r=><tr key={r.month} style={{borderBottom:"1px solid #f3f4f6"}}><td style={{padding:"6px 10px",textAlign:"right"}}>{r.label}</td><td style={{padding:"6px 10px",textAlign:"right",color:"#2563eb",fontWeight:r.actual>0?600:400}}>{r.actual>0?$(r.actual):"—"}</td><td style={{padding:"6px 10px",textAlign:"right",color:"#f59e0b",fontWeight:r.forecast>0?600:400}}>{r.forecast>0?$(r.forecast):"—"}</td></tr>)}<tr style={{background:"#f9fafb",borderTop:"2px solid #e5e7eb"}}><td style={{padding:8,textAlign:"right",fontWeight:700}}>TOTAL</td><td style={{padding:8,textAlign:"right",fontWeight:700,color:"#2563eb"}}>{$(tA)}</td><td style={{padding:8,textAlign:"right",fontWeight:700,color:"#f59e0b"}}>{$(tF)}</td></tr><tr style={{background:"#f0fdf4"}}><td style={{padding:8,textAlign:"right",fontWeight:700,color:"#16a34a"}}>Revenue</td><td colSpan={2} style={{padding:8,textAlign:"center",fontWeight:700,color:"#16a34a",fontSize:14}}>{$(tA+tF)}</td></tr><tr style={{background:delta>=0?"#fefce8":"#fef2f2"}}><td style={{padding:8,textAlign:"right",fontWeight:700,color:delta>=0?"#a16207":"#dc2626"}}>Delta</td><td colSpan={2} style={{padding:8,textAlign:"center",fontWeight:700,fontSize:14,color:delta>=0?"#a16207":"#dc2626"}}>{$(delta)}</td></tr></tbody></table></div>
      <div style={{background:"#fff",borderRadius:10,border:"1px solid #e5e7eb",padding:12}}><h4 style={{margin:"0 0 10px",fontSize:13}}>Activities</h4><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:"#f9fafb"}}>{["Activity","%","Value","Earned","Out."].map((h,i)=><th key={i} style={{padding:"6px 10px",textAlign:"left",fontWeight:600,color:"#6b7280",borderBottom:"1px solid #e5e7eb"}}>{h}</th>)}</tr></thead><tbody>{ls.map(l=>{const pc=l.pct>=80?"#16a34a":l.pct>=40?"#ca8a04":"#dc2626";return <tr key={l.id} style={{borderBottom:"1px solid #f3f4f6"}}><td style={{padding:"6px 10px"}}>{l.desc}</td><td style={{padding:"6px 10px"}}><span style={{background:pc+"22",color:pc,padding:"2px 8px",borderRadius:12,fontSize:10,fontWeight:600}}>{PCT(l.pct)}</span></td><td style={{padding:"6px 10px",fontWeight:600}}>{$(l.tv)}</td><td style={{padding:"6px 10px",fontWeight:600,color:"#2563eb"}}>{$(l.ev)}</td><td style={{padding:"6px 10px",fontWeight:600,color:"#dc2626"}}>{$(l.tv-l.ev)}</td></tr>;})}</tbody></table></div>
    </div>;
  };

  const views={Dashboard:Dash,Schedule:Sched,Resources:Res,Tracking:Track,Forecasting:Forecast,Reports:Reports};

  return <div style={{fontFamily:"-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif",background:"#f8fafc",minHeight:"100vh"}}>
    <div style={{background:"linear-gradient(135deg,#1e3a5f,#2563eb)",color:"#fff",padding:"12px 24px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:12}}><button onClick={onBack} style={{background:"rgba(255,255,255,.15)",border:"none",color:"#fff",borderRadius:6,padding:"6px 12px",cursor:"pointer",fontSize:12,fontWeight:600}}>← Back</button><div><h2 style={{margin:0,fontSize:17,fontWeight:700}}>{d.name}</h2><div style={{fontSize:11,opacity:.8}}>{d.mgr}</div></div></div><div style={{display:"flex",gap:12,alignItems:"center"}}>{[["Value",$(stats.tpv),"#fff"],["Earned",$(stats.el),"#86efac"]].map(([l,v,c])=><div key={l} style={{textAlign:"right"}}><div style={{fontSize:10,opacity:.7}}>{l}</div><div style={{fontSize:15,fontWeight:700,color:c}}>{v}</div></div>)}{confirmDel?<div style={{display:"flex",gap:4}}><span style={{fontSize:11,color:"#fca5a5"}}>Delete?</span><button onClick={()=>{onDelete();setConfirmDel(false);}} style={{background:"#dc2626",color:"#fff",border:"none",borderRadius:6,padding:"4px 10px",fontSize:11,fontWeight:600,cursor:"pointer"}}>Yes</button><button onClick={()=>setConfirmDel(false)} style={{background:"rgba(255,255,255,.2)",color:"#fff",border:"none",borderRadius:6,padding:"4px 10px",fontSize:11,fontWeight:600,cursor:"pointer"}}>No</button></div>:d.locked?<span style={{fontSize:11,color:"#fcd34d"}}>🔒</span>:<button onClick={()=>setConfirmDel(true)} style={{background:"rgba(255,255,255,.1)",border:"none",color:"#fca5a5",borderRadius:6,padding:"6px 10px",fontSize:11,fontWeight:600,cursor:"pointer"}}>🗑</button>}</div></div></div>
    <div style={{display:"flex",borderBottom:"2px solid #e5e7eb",background:"#fff",padding:"0 24px",overflow:"auto"}}>{Object.keys(views).map(t=><button key={t} onClick={()=>setTab(t)} style={ts(t)}>{t}</button>)}</div>
    <div style={{padding:"16px 24px",maxWidth:1200,margin:"0 auto"}}>{views[tab]()}</div>
    {modal&&<div style={{position:"fixed",inset:0,zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,.5)"}} onClick={()=>setModal(null)}><div style={{background:"#fff",borderRadius:12,padding:24,maxWidth:600,width:"90%",maxHeight:"80vh",overflow:"auto",boxShadow:"0 20px 60px rgba(0,0,0,.3)"}} onClick={e=>e.stopPropagation()}>
      <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><h3 style={{margin:0,fontSize:15}}>{({addLine:"Add Activity",editLine:"Edit Activity",addTender:"Add Tender",editTender:"Edit Tender",linkRes:"Link Resource",importSched:"Import Schedule",importBOQ:"Import BOQ"})[modal]}</h3><button onClick={()=>setModal(null)} style={{background:"none",border:"none",fontSize:18,cursor:"pointer"}}>✕</button></div>
      {(modal==="importSched"||modal==="importBOQ")&&<div><div style={{border:"2px dashed #d1d5db",borderRadius:10,padding:20,textAlign:"center",cursor:"pointer",marginBottom:10}} onClick={()=>fileRef.current?.click()}><input ref={fileRef} type="file" accept=".csv,.tsv,.txt" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setImpPreview(mapCSV(parseCSV(await f.text()),modal==="importSched"?normS:normB));}catch{}if(fileRef.current)fileRef.current.value="";}} style={{display:"none"}}/><div style={{fontSize:24}}>📄</div><div style={{fontSize:12,fontWeight:600}}>Upload CSV</div></div><textarea value={impText} onChange={e=>setImpText(e.target.value)} rows={3} placeholder="Or paste here" style={{width:"100%",padding:8,border:"1px solid #d1d5db",borderRadius:6,fontSize:11,fontFamily:"monospace",boxSizing:"border-box",marginBottom:4}}/><button onClick={()=>{if(!impText.trim())return;try{setImpPreview(mapCSV(parseCSV(impText),modal==="importSched"?normS:normB));}catch{}}} style={{background:"#f3f4f6",border:"none",borderRadius:6,padding:"4px 12px",fontSize:11,fontWeight:600,cursor:"pointer"}}>Parse</button>{impPreview&&impPreview.length>0&&<div style={{marginTop:8}}><div style={{fontSize:12,fontWeight:600,color:"#16a34a",marginBottom:4}}>✓ {impPreview.length} items</div><button onClick={()=>{if(modal==="importSched"){const items=impPreview.filter(r=>r.desc?.trim()).map((r,i)=>({id:uid(),rn:i+1,desc:r.desc.trim(),sd:r.sd||"",ed:r.ed||""}));setProj({...d,li:items,sli:[],act:[]});}else{const items=impPreview.filter(r=>r.desc?.trim()).map((r,i)=>({id:uid(),code:r.code||`T-${String(i+1).padStart(3,"0")}`,desc:r.desc.trim(),unit:r.unit||"ea",qty:Number(r.qty)||0,rate:Number(r.rate)||0}));setProj({...d,ti:items,sli:[],act:[]});}setImpPreview(null);setImpText("");setModal(null);}} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"6px 16px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Import</button></div>}</div>}
      {(modal==="addLine"||modal==="editLine")&&<div><div style={{marginBottom:8}}><label style={{fontSize:11,color:"#6b7280"}}>Description</label><input value={form.desc||""} onChange={e=>setForm({...form,desc:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><div><label style={{fontSize:11,color:"#6b7280"}}>Start</label><input type="date" value={form.sd||""} onChange={e=>setForm({...form,sd:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div><div><label style={{fontSize:11,color:"#6b7280"}}>End</label><input type="date" value={form.ed||""} onChange={e=>setForm({...form,ed:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div></div><div style={{display:"flex",gap:8,marginTop:12}}><button onClick={()=>{if(!form.desc?.trim())return;if(modal==="editLine")setProj({...d,li:d.li.map(l=>l.id===form.id?{...l,desc:form.desc,sd:form.sd,ed:form.ed}:l)});else setProj({...d,li:[...d.li,{id:uid(),rn:d.li.length+1,desc:form.desc,sd:form.sd,ed:form.ed}]});setModal(null);}} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Save</button><button onClick={()=>setModal(null)} style={{background:"#f3f4f6",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Cancel</button></div></div>}
      {(modal==="addTender"||modal==="editTender")&&<div><div style={{display:"grid",gridTemplateColumns:"1fr 2fr",gap:8}}><div><label style={{fontSize:11,color:"#6b7280"}}>Code</label><input value={form.code||""} onChange={e=>setForm({...form,code:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div><div><label style={{fontSize:11,color:"#6b7280"}}>Desc</label><input value={form.desc||""} onChange={e=>setForm({...form,desc:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginTop:8}}><div><label style={{fontSize:11,color:"#6b7280"}}>Unit</label><input value={form.unit||""} onChange={e=>setForm({...form,unit:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div><div><label style={{fontSize:11,color:"#6b7280"}}>Qty</label><input type="number" value={form.qty||""} onChange={e=>setForm({...form,qty:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div><div><label style={{fontSize:11,color:"#6b7280"}}>Rate</label><input type="number" value={form.rate||""} onChange={e=>setForm({...form,rate:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div></div><div style={{display:"flex",gap:8,marginTop:12}}><button onClick={()=>{if(!form.desc?.trim())return;if(modal==="editTender")setProj({...d,ti:d.ti.map(t=>t.id===form.id?{...t,code:form.code,desc:form.desc,unit:form.unit,qty:Number(form.qty)||0,rate:Number(form.rate)||0}:t)});else setProj({...d,ti:[...d.ti,{id:uid(),code:form.code||`T-${String(d.ti.length+1).padStart(3,"0")}`,desc:form.desc,unit:form.unit||"ea",qty:Number(form.qty)||0,rate:Number(form.rate)||0}]});setModal(null);}} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Save</button><button onClick={()=>setModal(null)} style={{background:"#f3f4f6",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Cancel</button></div></div>}
      {modal==="linkRes"&&<div><div style={{marginBottom:8}}><label style={{fontSize:11,color:"#6b7280"}}>Activity</label><select value={form.liId||""} onChange={e=>setForm({...form,liId:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box",background:"#fff"}}><option value="">Select...</option>{d.li.map(l=><option key={l.id} value={l.id}>#{l.rn} {l.desc}</option>)}</select></div><div style={{marginBottom:8}}><label style={{fontSize:11,color:"#6b7280"}}>Tender</label><select value={form.tiId||""} onChange={e=>{const t=d.ti.find(x=>x.id===e.target.value);setForm({...form,tiId:e.target.value,alloc:t?String(t.qty):""});}} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box",background:"#fff"}}><option value="">Select...</option>{d.ti.map(t=><option key={t.id} value={t.id}>{t.code} — {t.desc}</option>)}</select></div><div style={{marginBottom:8}}><label style={{fontSize:11,color:"#6b7280"}}>Qty</label><input type="number" value={form.alloc||""} onChange={e=>setForm({...form,alloc:e.target.value})} style={{width:"100%",padding:"8px 12px",border:"1px solid #d1d5db",borderRadius:6,fontSize:13,boxSizing:"border-box"}}/></div><div style={{display:"flex",gap:8}}><button onClick={()=>{if(!form.liId||!form.tiId||!form.alloc)return;setProj({...d,sli:[...d.sli,{id:uid(),liId:form.liId,tiId:form.tiId,alloc:Number(form.alloc)}]});setModal(null);}} style={{background:"#2563eb",color:"#fff",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Link</button><button onClick={()=>setModal(null)} style={{background:"#f3f4f6",border:"none",borderRadius:6,padding:"8px 18px",fontSize:12,fontWeight:600,cursor:"pointer"}}>Cancel</button></div></div>}
    </div></div>}
  </div>;
}